### ISSUE TITLE
New page error "try again" may fail due to invisibleItemsThreshold

### ISSUE THREAD

**Issue by dbmessina** [EdsonBueno/infinite_scroll_pagination#332]
In my app, I was experiencing the behavior of pressing "try again" on a new page error and it would switch to the loading spinner indefinitely as it was never making a new page request. Eventually I found the solution to be lowering my invisibleItemsThreshold which I had set to 10. At least on my device, any value of 8 or less will work. However, I believe this is a bug as I don't understand why a threshold intended for scrolling should have any impact on a manual request.

This can be easily reproduced in the example app by setting a high invisibleItemsThreshold assuming you've replaced the defunct API it uses with something else.

**Comment by clragon** [comment]
The reason for this is that the way the retry button works is by clearing the error. 
Once the error is cleared, the layout would get updated and set its flag for having requested a page back to false.
Then, once the threshold item is built, a new page would be requested. 

A situation where the threshold item is not in view when this happens is rare, but with a high threshold, imaginable.
I will see if I can fix this.

**Comment by clragon** [comment]
I believe this issue was caused by a off-by-one issue in `invisibleItemsThreshold`, which we have fixed in version 5.

**Comment by JetA2** [comment]
It looks like this could still happen in v5 if paging is restarted and the trigger item will not be rebuilt, since it's off screen.
This happens even with a low threshold in lists with large items (social media posts for example).
